languageCode = "en-us"
baseURL = "/"
title = "Felix in Japan"
theme = "internet-weblog"
Paginate = 10
SectionPagesMenu = "main"
#publishdir = "docs"

[author]
	Handle = "Felix"
	FirstName = "Felix"
	LastName = "Dollack"
	AboutPage = "/about"
	Location = "Tsukuba, Japan"
	FlickrID = "149203503@N04"

[params]
	DateFormPost = "02. Jan 2006"
	DateFormMini = "2006/01/02 3:04 PM"
	Description = "This is my blog, read it and enjoy."
	ShowCopyright = true
	RSSEnabled = true
	RSSSections = [ "Blog" ] #, "Microposts", "Photos" ]

[taxonomies]
	tag = "tags"
	category = "categories"
	series = "series"

[[menu.main]]
  name = "Blog"
  weight = 1
	identifier = "posts"
  url = "/posts/"

[[menu.main]]
	name = "Mini's"
	weight = 2
	identifier = "microposts"
	url = "/microposts/"

#[[menu.main]]
#	name = "Photos"
#	weight = 3
#	identifier = "photos"
#	url = "/photos/"
